import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report={passed:[],errors:[],requests:[]};const base=process.env.TEST_URL||'http://localhost:5173';
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>report.requests.push(r.url()));await page.goto(base+'/?test=1');await page.waitForFunction(()=>!!window.__game);await page.screenshot({path:'test-results/menu-desktop.png'});
 await page.evaluate(()=>{const g=window.__game;g.capture=()=>{};g.start();});await page.waitForTimeout(1200);
 assert.equal(await page.evaluate(()=>window.__game.state),'playing');report.passed.push('Start and renderer');
 assert.ok(await page.evaluate(()=>window.__game.enemies.active.length)>0);report.passed.push('Wave 1 spawns enemies');
 const movement=await page.evaluate(()=>{const g=window.__game,before=g.player.position.z;g.input.keys.add('KeyW');for(let i=0;i<30;i++)g.player.update(1/60,g.input,g.map,g.renderer.camera);g.input.keys.clear();return before-g.player.position.z;});assert.ok(movement>1);report.passed.push('PC movement');
 const combat=await page.evaluate(()=>{const g=window.__game;g.enemies.pool.forEach(e=>e.die());g.player.position.set(0,0,25);g.player.pitch=0;g.player.yaw=0;g.player.update(.016,g.input,g.map,g.renderer.camera);const e=g.enemies.pool[0];e.spawn(g.player.position.clone().set(0,0,20),1);g.renderer.scene.updateMatrixWorld(true);g.weapons.switch(2);g.shoot(0);return{active:e.active,kills:g.enemies.kills,hits:g.weapons.hits};});assert.equal(combat.active,false);assert.ok(combat.kills>0);report.passed.push('Head hitbox, sniper headshot and kill');
 const wall=await page.evaluate(()=>{const g=window.__game,e=g.enemies.pool[0];g.player.position.set(0,0,10);g.player.pitch=0;g.player.yaw=0;g.player.update(.016,g.input,g.map,g.renderer.camera);e.spawn(g.player.position.clone().set(0,0,-8),1);g.renderer.scene.updateMatrixWorld(true);g.shoot(0);return e.hp;});assert.equal(wall,100);report.passed.push('World geometry blocks hitscan');
 const reload=await page.evaluate(()=>{const g=window.__game;g.weapons.switch(0);g.weapons.current.ammo=0;g.weapons.reload();g.weapons.update(2.1,g.input,g.player,()=>{});return[g.weapons.current.ammo,g.weapons.current.reserve];});assert.deepEqual(reload,[30,90]);report.passed.push('Reload ammo conservation');
 const actions=await page.evaluate(()=>{const g=window.__game;g.input.jump=true;g.player.update(.016,g.input,g.map,g.renderer.camera);const jump=g.player.position.y>0;g.input.crouch=true;g.player.update(.2,g.input,g.map,g.renderer.camera);return{jump,crouch:g.player.height<1.2};});assert.ok(actions.jump&&actions.crouch);report.passed.push('Jump and crouch');
 await page.evaluate(()=>{const g=window.__game;g.player.position.set(8,0,14);g.player.yaw=.3;g.player.pitch=0;g.player.update(.016,g.input,g.map,g.renderer.camera);g.input.crouch=false;});await page.waitForTimeout(100);await page.screenshot({path:'test-results/game-desktop.png'});
 const ai=await page.evaluate(()=>{const g=window.__game;g.enemies.reset();g.player.position.set(0,0,25);g.player.update(.016,g.input,g.map,g.renderer.camera);g.enemies.pool[0].spawn(g.player.position.clone().set(0,0,20),1);let damage=0;for(let i=0;i<500;i++)g.enemies.update(.04,g.player,g.renderer.camera,n=>damage+=n,()=>{});return damage;});assert.ok(ai>0);report.passed.push('Enemy AI attacks and inflicts damage');
 const pickups=await page.evaluate(()=>{const g=window.__game;g.pickups.reset();g.player.hp=30;g.player.position.copy(g.pickups.items[0].mesh.position).setY(0);g.pickups.update(.016,g.player,g.weapons,()=>{});const hp=g.player.hp;const before=g.weapons.current.reserve;g.player.position.copy(g.pickups.items[1].mesh.position).setY(0);g.pickups.update(.016,g.player,g.weapons,()=>{});return{hp,ammo:g.weapons.current.reserve>before};});assert.equal(pickups.hp,65);assert.ok(pickups.ammo);report.passed.push('Health and ammo pickups');
 await page.evaluate(()=>window.__game.damage(1000));assert.equal(await page.evaluate(()=>window.__game.state),'over');await page.screenshot({path:'test-results/gameover.png'});await page.click('#restart');assert.equal(await page.evaluate(()=>window.__game.player.hp),100);report.passed.push('Game over and restart reset');
 const routes=await page.evaluate(()=>{const g=window.__game;return g.map.spawns.map(p=>g.map.path(p,g.player.position).length);});assert.ok(routes.every(n=>n>0));report.passed.push('All spawn areas connected to player via waypoint graph');
 await page.close();
 const mobile=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:3});const p=await mobile.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'/?test=1');await p.waitForFunction(()=>!!window.__game);await p.evaluate(()=>{window.__game.capture=()=>{};window.__game.start();});await p.waitForTimeout(300);
 assert.ok(await p.locator('#mobile-controls').isVisible());assert.ok(await p.evaluate(()=>window.__game.renderer.gl.getPixelRatio())<=1.5);
 const client=await mobile.newCDPSession(p);const joy=await p.locator('#joystick').boundingBox(),fire=await p.locator('[data-action="fire"]').boundingBox();const touches=[{id:1,x:joy.x+joy.width/2,y:joy.y+joy.height/2},{id:2,x:440,y:150},{id:3,x:fire.x+fire.width/2,y:fire.y+fire.height/2}];const before=await p.evaluate(()=>({yaw:window.__game.player.yaw,z:window.__game.player.position.z,shots:window.__game.weapons.shots}));
 await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:touches});touches[0].y-=30;touches[1].x+=40;await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:touches});await p.waitForTimeout(400);
 const after=await p.evaluate(()=>({yaw:window.__game.player.yaw,z:window.__game.player.position.z,shots:window.__game.weapons.shots}));assert.notEqual(before.yaw,after.yaw);assert.ok(after.z<before.z);assert.ok(after.shots>before.shots);report.passed.push('Three simultaneous real touch pointers: move + look + fire');
 await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await p.evaluate(()=>window.__game.input.fire),false);report.passed.push('Touch release clears fire');
 await p.screenshot({path:'test-results/game-mobile.png'});await p.setViewportSize({width:390,height:844});assert.ok(await p.locator('#rotate').isVisible());report.passed.push('Portrait rotation overlay');
 assert.equal(report.errors.length,0,report.errors.join('\n'));report.passed.push('No uncaught browser errors');console.log(JSON.stringify(report,null,2));
}finally{await writeFile('test-results/report.json',JSON.stringify(report,null,2));await browser.close();}

