import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const b=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const passed=[];try{const p=await b.newPage();await p.goto('http://localhost:5174/?test=1');await p.waitForFunction(()=>!!window.__game);const result=await p.evaluate(()=>{const g=window.__game;g.capture=()=>{};g.lobby.mode='survival';g.start();g.state='paused';g.enemies.reset();g.player.reset();g.player.update(.016,g.input,g.map,g.renderer.camera);let e=g.enemies.pool[0];e.spawn(g.player.position.clone().set(0,0,20),1);g.weapons.switch(2);g.shoot(0);const head=!e.active&&g.headshots===1;e.spawn(g.player.position.clone().set(0,0,20),1);g.weapons.switch(0);g.player.pitch=Math.atan2(1.05-1.65,7);g.player.update(.016,g.input,g.map,g.renderer.camera);g.shoot(0);const body=e.hp===70;
g.player.position.set(-13,0,26);g.player.yaw=0;g.player.pitch=0;g.player.update(.016,g.input,g.map,g.renderer.camera);e.spawn(g.player.position.clone().set(-13,0,0),1);g.shoot(0);const wall=e.hp===100;
g.player.reset();g.player.update(.016,g.input,g.map,g.renderer.camera);e.spawn(g.player.position.clone().set(0,0,20),1);g.renderer.scene.updateMatrixWorld(true);g.skills.reset('jiying');g.skills.cast(1,g.input,g.renderer.camera);for(let i=0;i<120;i++){g.skills.update(.02,g.input,g.renderer.camera);g.zombies.fx.update(.02,g.player.position,()=>{});g.effects.update(.02);}const grenade=e.hp<100;
g.skills.reset('tiansun');e.spawn(g.player.position.clone().set(0,0,20),1);g.skills.cast(1,g.input,g.renderer.camera);for(let i=0;i<50;i++){g.skills.update(.02,g.input,g.renderer.camera);g.zombies.fx.update(.02,g.player.position,()=>{});g.effects.update(.02);}const delayed=e.hp===100;for(let i=0;i<100;i++){g.skills.update(.02,g.input,g.renderer.camera);g.zombies.fx.update(.02,g.player.position,()=>{});g.effects.update(.02);}const sticky=e.hp<100;
g.skills.reset('yuehen');e.spawn(g.player.position.clone().set(0,0,20),1);g.skills.cast(1,g.input,g.renderer.camera);for(let i=0;i<150;i++){g.skills.update(.02,g.input,g.renderer.camera);g.zombies.fx.update(.02,g.player.position,()=>{});g.effects.update(.02);}const arc=e.hp<100;
g.enemies.pool.forEach(e=>e.die());g.renderer.setQuality('LOW');for(let i=0;i<8;i++)g.enemies.pool[i].spawn(g.player.position.clone().set((i%4)*2-3,0,20-Math.floor(i/4)*3),1);g.renderer.scene.updateMatrixWorld(true);g.enemies.pool.forEach(e=>e.lod.update(g.renderer.camera));g.renderer.render();const budget={calls:g.renderer.gl.info.render.calls,triangles:g.renderer.gl.info.render.triangles,textures:g.renderer.gl.info.memory.textures};
g.player.position.set(22,0,21);for(let i=0;i<100;i++){g.map.move(g.player.position,0,-.12);g.player.position.y=g.map.groundAt(g.player.position.x,g.player.position.z);}const ramp=g.player.position.y>2;g.player.position.set(26,0,8);g.map.move(g.player.position,-1.1,0);const cliff=g.player.position.x===26;
return {head,body,wall,grenade,delayed,sticky,arc,ramp,cliff,budget};});for(const key of ['head','body','wall','grenade','delayed','sticky','arc','ramp','cliff'])assert.ok(result[key],key+' failed '+JSON.stringify(result));assert.ok(result.budget.calls<180);assert.ok(result.budget.triangles<200000);passed.push('Head/body hitscan and wall occlusion','Grenade impact AOE, delayed sticky detonation, arc damage','Ramp elevation and cliff collision','LOW draw-call and triangle budgets with 8 enemies');await writeFile('test-results/combat-v2.json',JSON.stringify({passed,result},null,2));console.log(result);}finally{await b.close();}
const wb=await webkit.launch({headless:true});try{const c=await wb.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:5174/?test=1');await p.waitForFunction(()=>!!window.__game);await p.evaluate(()=>window.__game.capture=()=>{});await p.locator('#play').tap();await p.locator('[data-mode="survival"]').tap();await p.locator('[data-op="shouwang"]').tap();await p.locator('#operator-equip').tap();await p.locator('#deploy-start').tap();await p.locator('[data-action="ads"]').tap();await p.locator('[data-action="fire"]').tap();await p.waitForFunction(()=>window.__game.weapons.shots>0);await p.locator('#skill2').tap();await p.waitForFunction(()=>window.__game.player.armor>0);assert.equal(errors.length,0);await p.screenshot({path:'test-results/twinkle-webkit.png'});await writeFile('test-results/webkit-v2.json',JSON.stringify({pass:true,checks:['lobby','operator','loadout','ADS','fire','armor'],errors},null,2));console.log('WebKit mobile flow passed');}finally{await wb.close();}
