import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('test-results',{recursive:true});const passed=[],errors=[];const browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:5174/?test=1');await p.waitForFunction(()=>!!window.__game,{},{timeout:60000});await p.click('#play');await p.screenshot({path:'test-results/pve-mode-select.png'});await p.click('[data-mode="last-sector"]');await p.click('#operator-equip');await p.click('[data-weapon="M249"]');await p.click('#equip-weapon');await p.evaluate(()=>window.__game.capture=()=>{});await p.click('#deploy-start');await p.waitForFunction(()=>window.__game.state==='playing');assert.equal(await p.evaluate(()=>window.__game.weapons.current.spec.id),'M249');passed.push('Mode > operator > M249 loadout > actual PVE deployment');
const result=await p.evaluate(()=>{const g=window.__game;g.state='paused';g.input.reset();const pool=g.zombies;
function reset(){pool.reset();pool.remaining=0;pool.nextHorde=9999;g.player.reset();g.player.update(.016,g.input,g.map,g.renderer.camera);g.renderer.scene.updateMatrixWorld(true);}
reset();let skinned=0;pool.zombies[0].near.model.traverse(o=>{if(o.isSkinnedMesh&&o.material.normalMap)skinned++;});
const sp=pool.spawnKind('spitter',g.player.position.clone().set(0,0,17));let sawProjectile=false;let acidDamage=0;for(let i=0;i<240;i++){g.renderer.scene.updateMatrixWorld(true);pool.update(.02,g.player,g.renderer.camera,n=>acidDamage+=n,()=>{});sawProjectile ||= pool.fx.projectiles.some(p=>p.life>0);}const puddles=pool.fx.pools.some(p=>p.life>0);const outside=g.player.position.clone().set(7,0,27);let avoided=0;for(let i=0;i<30;i++)pool.fx.update(.02,outside,n=>avoided+=n);
reset();g.weapons.switch(0);g.player.pitch=Math.atan2(1.1-1.65,7);g.player.update(.016,g.input,g.map,g.renderer.camera);const bomb=pool.spawnKind('bomber',g.player.position.clone().set(0,0,20)),other=pool.spawnKind('infected',g.player.position.clone().set(2,0,20)),bomb2=pool.spawnKind('bomber',g.player.position.clone().set(-1.5,0,20));g.shoot(0);const weakHP=bomb.hp;g.shoot(0);const chain=!bomb.active&&!other.active&&!bomb2.active;const death=other.corpse>0&&other.root.visible;
reset();const pouncer=pool.spawnKind('pouncer',g.player.position.clone().set(0,0,20));pouncer.specialCooldown=0;let telegraph=false,leapt=false,airHitbox=false;for(let i=0;i<100&&!pool.pinned;i++){g.renderer.scene.updateMatrixWorld(true);pool.update(.02,g.player,g.renderer.camera,()=>{},()=>{});telegraph ||= pouncer.windup>0;leapt ||= pouncer.leap>0;airHitbox ||= pouncer.root.position.y>.2;}const pinned=pool.pinned===pouncer;for(let i=0;i<5;i++)pool.struggle();const escaped=!pool.pinned&&pool.immunity>0;
g.campaign.openGate(0);g.campaign.openGate(1);const routes=g.operation.stops.map(s=>({blocked:g.map.blocked(s.pos.x,s.pos.z,.4),path:g.map.path(g.player.position,s.pos).length}));g.operation.reset();for(let stage=0;stage<g.operation.stops.length;stage++){g.player.position.copy(g.operation.stops[stage].pos);g.operation.interact=true;if(stage===8){const boss=pool.zombies.find(z=>z.kind==='titan'&&z.active);if(boss)g.hitEnemy(boss,9999);}const duration=g.operation.stops[stage].seconds;for(let t=0;t<duration+.1;t+=.1)g.operation.update(.1,g.player,()=>{});}const extracted=g.operation.complete;
reset();g.renderer.setQuality('LOW');g.setEnemyBudget();for(let i=0;i<20;i++)pool.spawnKind('infected',g.player.position.clone().set((i%5)*1.5-3,0,20-Math.floor(i/5)*1.8));pool.zombies.forEach(z=>{z.animate(.05,g.renderer.camera);});g.renderer.scene.updateMatrixWorld(true);g.renderer.render();const budget={calls:g.renderer.gl.info.render.calls,triangles:g.renderer.gl.info.render.triangles,textures:g.renderer.gl.info.memory.textures,cap:pool.maxActive,poolSize:pool.pool.length};return{skinned,sawProjectile,acidDamage,puddles,avoided,weakHP,chain,death,telegraph,leapt,airHitbox,pinned,escaped,routes,extracted,budget};});
assert.ok(result.skinned>=2);for(const k of ['sawProjectile','puddles','chain','death','telegraph','leapt','airHitbox','pinned','escaped','extracted'])assert.ok(result[k],k+' '+JSON.stringify(result));assert.ok(result.acidDamage>0);assert.equal(result.avoided,0);assert.ok(result.weakHP<70);assert.ok(result.routes.every(r=>!r.blocked&&r.path>0));assert.equal(result.budget.cap,20);assert.ok(result.budget.calls<260);assert.ok(result.budget.triangles<400000);passed.push('Skinned GLB and local normal maps','Visible ballistic spit, damaging pools, moving away avoids acid','Sac weakpoint and chain explosions; pooled death animation','Pounce telegraph, leap, pin and five-tap escape','Objective route through ten campaign objectives and successful extraction','20-enemy LOW render budget');await p.screenshot({path:'test-results/pve-horde-low.png'});
// Touch regression keeps three independent physical touch contacts active.
const c=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const m=await c.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto('http://localhost:5174/?test=1');await m.waitForFunction(()=>!!window.__game,{},{timeout:60000});await m.evaluate(()=>window.__game.capture=()=>{});await m.locator('#play').tap();await m.locator('[data-mode="last-sector"]').tap();await m.locator('#operator-equip').tap();await m.locator('#deploy-start').tap();await m.locator('#joystick').waitFor({state:'visible'});const cd=await c.newCDPSession(m),joy=await m.locator('#joystick').boundingBox(),fire=await m.locator('[data-action="fire"]').boundingBox();const touches=[{id:1,x:joy.x+58,y:joy.y+58},{id:2,x:410,y:150},{id:3,x:fire.x+fire.width/2,y:fire.y+fire.height/2}];await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:touches});touches[0].y-=30;touches[1].x+=40;await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:touches});await m.waitForFunction(()=>window.__game.player.position.z<27&&window.__game.player.yaw<0&&window.__game.weapons.shots>0);await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await m.evaluate(()=>{const g=window.__game;g.zombies.reset();g.zombies.remaining=0;const z=g.zombies.spawnKind('pouncer',g.player.position.clone());g.zombies.pinned=z;});await m.locator('#struggle').waitFor({state:'visible'});for(let i=0;i<5;i++)await m.locator('#struggle').tap();await m.waitForFunction(()=>!window.__game.zombies.pinned);passed.push('Mobile three-touch move/look/fire plus visible TAP escape button');await m.screenshot({path:'test-results/pve-mobile.png'});assert.equal(errors.length,0,errors.join('\n'));await writeFile('test-results/pve-report.json',JSON.stringify({passed,result,errors},null,2));console.log({passed,result,errors});
}finally{await browser.close();}
