import {chromium} from 'playwright';import {createServer} from 'node:http';import {readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
let upgraded=false;const root=path.resolve('dist');const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/blue-sector/')){res.writeHead(404).end();return;}const relative=decodeURIComponent(url.pathname.slice('/blue-sector/'.length))||'index.html',file=path.resolve(root,relative);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{let body=await readFile(file);if(relative==='sw.js'&&upgraded)body=Buffer.from(body.toString().replace(/const CACHE=PREFIX\+'[^']+'/,"const CACHE=PREFIX+'test-updated-release'"));res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(body);}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(4182,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const results=[];const errors=[];try{const context=await browser.newContext();const page=await context.newPage();const requests=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4182/blue-sector/?test=1');await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);await page.waitForFunction(()=>!!window.__game);await page.waitForTimeout(500);await page.reload();await page.waitForFunction(()=>!!window.__game);assert.ok(requests.every(u=>u.startsWith('http://127.0.0.1:4182/')));results.push('All production requests are same-origin under repository subpath');
 await context.setOffline(true);await page.reload();await page.waitForFunction(()=>!!window.__game);await page.evaluate(()=>{window.__game.capture=()=>{};window.__game.start();});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.__game.state),'playing');results.push('Offline reload and playable cached game');
 await context.setOffline(false);upgraded=true;await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await page.waitForFunction(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting);await page.reload();await page.waitForSelector('#update-notice:not(.hidden)');await page.click('#update');await page.waitForFunction(async()=>{const keys=await caches.keys();return keys.some(k=>k.endsWith('test-updated-release'));});await page.waitForFunction(()=>!!window.__game);const keys=await page.evaluate(()=>caches.keys());assert.equal(keys.filter(k=>k.startsWith('blue-sector-')).length,1);results.push('Explicit update switches service worker, reloads and removes old version');
 assert.equal(errors.length,0,errors.join('\n'));await writeFile('test-results/pwa-report.json',JSON.stringify({results,requests,errors},null,2));console.log(results);
}finally{await browser.close();server.close();}

