import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';await mkdir('test-results',{recursive:true});
const b=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report={passed:[],errors:[]};try{const page=await b.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});await page.goto('http://localhost:5174/?test=1');await page.waitForFunction(()=>!!window.__game);await page.screenshot({path:'test-results/twinkle-lobby.png'});await page.click('#play');assert.ok(await page.locator('[data-op="yuehen"]').isVisible());await page.click('[data-op="yuehen"]');await page.click('#operator-equip');assert.ok(await page.locator('#deploy-start').isVisible());report.passed.push('Lobby > operator > loadout > deploy flow');
await page.selectOption('[data-attachment="scope"]','4x');await page.selectOption('[data-attachment="magazine"]','extended');await page.selectOption('[data-attachment="muzzle"]','compensator');await page.screenshot({path:'test-results/twinkle-gunsmith.png'});
await page.evaluate(()=>{window.__game.capture=()=>{};});await page.click('#deploy-start');await page.waitForFunction(()=>window.__game.state==='playing');const loadout=await page.evaluate(()=>{const g=window.__game;return{operator:g.skills.operator,ammo:g.weapons.current.ammo,scope:g.weapons.current.attachments.scope,recoil:g.weapons.current.spec.recoil,base:g.weapons.current.base.recoil};});assert.equal(loadout.operator,'yuehen');assert.equal(loadout.ammo,40);assert.equal(loadout.scope,'4x');assert.ok(loadout.recoil<loadout.base);report.passed.push('Attachments change magazine and recoil; operator applied');
await page.evaluate(()=>window.__game.input.ads=true);await page.waitForFunction(()=>window.__game.renderer.camera.fov<25);assert.ok(await page.evaluate(()=>window.__game.renderer.camera.fov)<25);report.passed.push('4x changes actual FOV');await page.evaluate(()=>window.__game.input.ads=false);
const settle=await page.evaluate(()=>{const g=window.__game;g.enemies.kills=20;g.headshots=5;g.enemies.wave=4;g.elapsed=100;g.over();const once=g.profile.data.credits;g.over();return{once,twice:g.profile.data.credits};});assert.equal(settle.once,900);assert.equal(settle.twice,900);report.passed.push('Credits settlement idempotent and based on stats');
await page.click('#back-menu');await page.click('[data-tab="weapons"]');await page.click('[data-weapon="HP-45"]');await page.click('#equip-weapon');assert.equal(await page.evaluate(()=>window.__game.profile.data.credits),0);assert.equal(await page.evaluate(()=>window.__game.profile.data.secondary),'HP-45');await page.reload();await page.waitForFunction(()=>!!window.__game);assert.equal(await page.evaluate(()=>window.__game.profile.data.secondary),'HP-45');assert.equal(await page.evaluate(()=>window.__game.profile.getAttachments('AR-01').scope),'4x');report.passed.push('Buy/equip spends credits once; reload persists loadout and attachments');
const abilities=await page.evaluate(()=>{const g=window.__game;g.capture=()=>{};g.start();g.state='paused';const result={};g.skills.reset('jiying');result.overload=g.skills.cast(0,g.input,g.renderer.camera)&&g.skills.overload===8;const cd=g.skills.cooldowns[0];g.skills.cast(0,g.input,g.renderer.camera);result.cooldown=g.skills.cooldowns[0]===cd;g.skills.onKill();result.extension=g.skills.overload>8;g.skills.reset('tiansun');g.player.position.set(0,0,27);g.player.yaw=0;g.skills.cast(0,g.input,g.renderer.camera);for(let i=0;i<11;i++)g.skills.update(.02,g.input,g.renderer.camera);result.dash=27-g.player.position.z>7&&!g.map.blocked(g.player.position.x,g.player.position.z);g.skills.reset('yuehen');g.enemies.pool.forEach(e=>e.die());const e=g.enemies.pool[0];e.spawn(g.player.position.clone().add({x:2,y:0,z:0}),1);g.skills.cast(2,g.input,g.renderer.camera);g.skills.update(.1,g.input,g.renderer.camera);result.reveal=e.reveal>0;g.skills.reset('shouwang');g.player.hp=40;g.skills.cast(0,g.input,g.renderer.camera);g.skills.update(.1,g.input,g.renderer.camera);result.heal=g.player.hp>40;g.skills.cast(2,g.input,g.renderer.camera);result.armor=g.player.armor===60;return result;});assert.ok(Object.values(abilities).every(Boolean),JSON.stringify(abilities));report.passed.push('Overload, cooldown, kill extension, collision-aware dash, reveal, heal, armor');
await page.close();const mobile=await b.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const p=await mobile.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://localhost:5174/?test=1');await p.waitForFunction(()=>!!window.__game);await p.screenshot({path:'test-results/twinkle-lobby-mobile.png'});await p.evaluate(()=>window.__game.capture=()=>{});await p.locator('#play').tap();await p.locator('[data-op="tiansun"]').tap();await p.locator('#operator-equip').tap();await p.locator('#deploy-start').tap();await p.waitForFunction(()=>window.__game.state==='playing');
const cd=await mobile.newCDPSession(p),joy=await p.locator('#joystick').boundingBox(),fire=await p.locator('[data-action="fire"]').boundingBox();const ts=[{id:1,x:joy.x+58,y:joy.y+58},{id:2,x:410,y:150},{id:3,x:fire.x+fire.width/2,y:fire.y+fire.height/2}];await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:ts});ts[0].y-=30;ts[1].x+=40;await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:ts});await p.waitForTimeout(350);assert.ok(await p.evaluate(()=>window.__game.player.position.z<27&&window.__game.player.yaw<0&&window.__game.weapons.shots>0));await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.locator('#skill0').tap();await p.waitForFunction(()=>window.__game.skills.cooldowns[0]>0);await p.screenshot({path:'test-results/twinkle-game-mobile.png'});report.passed.push('Mobile lobby and three-touch move/look/fire preserved; skill button works');assert.equal(report.errors.length,0,report.errors.join('\n'));console.log(report);await writeFile('test-results/upgrade-report.json',JSON.stringify(report,null,2));}finally{await b.close();}


