type Layout={x:number;y:number;size:number;opacity:number};
export class HUDLayout {
    data:Record<string,Layout>={};selected='fire';editing=false;
    readonly defaults:Record<string,Layout>=Object.fromEntries(['fire','ads','reload','jump','crouch','switch','skill0','skill1','skill2'].map((key,i)=>[key,{x:[.86,.73,.67,.92,.81,.60,.37,.45,.53][i],y:[.48,.52,.80,.76,.83,.86,.84,.84,.84][i],size:1,opacity:.7}]));
    constructor(){try{const saved=JSON.parse(localStorage.getItem('twinkle-hud')||'{}');for(const key in this.defaults){const a=saved[key];if(a&&[a.x,a.y,a.size,a.opacity].every(Number.isFinite))this.data[key]={x:Math.max(.04,Math.min(.96,a.x)),y:Math.max(.06,Math.min(.94,a.y)),size:Math.max(.5,Math.min(1.5,a.size)),opacity:Math.max(.2,Math.min(1,a.opacity))};}}catch{}
        document.querySelector('#settings-close')!.insertAdjacentHTML('beforebegin','<button id="hud-edit" class="secondary">CUSTOMIZE HUD / 自定义按键</button>');
        document.querySelector('#app')!.insertAdjacentHTML('beforeend',`<section id="hud-editor" class="hidden"><div id="hud-editor-panel"><b>拖动按钮 · <span id="hud-selected">FIRE</span></b><label>大小 <input id="hud-size" type="range" min=".5" max="1.5" step=".05"></label><label>透明度 <input id="hud-opacity" type="range" min=".2" max="1" step=".05"></label><button id="hud-reset">重置</button><button id="hud-save">保存并返回</button></div></section>`);
        document.getElementById('hud-edit')!.onclick=()=>this.open();document.getElementById('hud-save')!.onclick=()=>{try{localStorage.setItem('twinkle-hud',JSON.stringify(this.data));}catch{}this.editing=false;document.getElementById('hud-editor')!.classList.add('hidden');this.apply();};
        document.getElementById('hud-reset')!.onclick=()=>{this.data=structuredClone(this.defaults);this.render();};
        for(const field of ['size','opacity'] as const)(document.getElementById('hud-'+field) as HTMLInputElement).oninput=e=>{this.data[this.selected][field]=Number((e.target as HTMLInputElement).value);this.render();};
        addEventListener('resize',()=>{this.apply();if(this.editing)this.render();});this.apply();
    }
    position(el:HTMLElement,a:Layout){const size=64*a.size;Object.assign(el.style,{position:'fixed',left:`clamp(max(20px, env(safe-area-inset-left)), ${a.x*innerWidth-size/2}px, calc(100vw - ${size+20}px - env(safe-area-inset-right)))`,top:`clamp(max(12px, env(safe-area-inset-top)), ${a.y*innerHeight-size/2}px, calc(100vh - ${size+12}px - env(safe-area-inset-bottom)))`,right:'auto',bottom:'auto',width:size+'px',height:size+'px',transform:'none',opacity:String(a.opacity),margin:'0'});}
    apply(){for(const [key,a] of Object.entries(this.data)){const el=document.querySelector<HTMLElement>(`[data-action="${key}"]`);if(el)this.position(el,a);}document.body.classList.toggle('custom-hud',Object.keys(this.data).length>0);}
    open(){this.editing=true;for(const key in this.defaults)this.data[key]??={...this.defaults[key]};document.getElementById('hud-editor')!.classList.remove('hidden');this.render();}
    render(){const root=document.getElementById('hud-editor')!;root.querySelectorAll('.hud-draggable').forEach(e=>e.remove());for(const [key,a] of Object.entries(this.data)){const b=document.createElement('button');b.className='hud-draggable';b.dataset.edit=key;b.textContent=key.toUpperCase();this.position(b,a);root.append(b);b.onpointerdown=e=>{e.preventDefault();this.selected=key;this.controls();b.setPointerCapture(e.pointerId);};b.onpointermove=e=>{if(!b.hasPointerCapture(e.pointerId))return;a.x=Math.max(.04,Math.min(.96,e.clientX/innerWidth));a.y=Math.max(.06,Math.min(.94,e.clientY/innerHeight));this.position(b,a);};}this.controls();}
    controls(){document.getElementById('hud-selected')!.textContent=this.selected.toUpperCase();for(const key of ['size','opacity'] as const)(document.getElementById('hud-'+key) as HTMLInputElement).value=String(this.data[this.selected][key]);}
}
